version: '2'

services:

  db:
    #restart: always
    image: postgres:10.5
    container_name: tt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd@1
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - TZ=Asia/Manila
    volumes:
      - ./docker/db/dbini:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5438:5432" # Only for tests
    networks:
      - tt

  tt-api:
    build:
      context: first_digital_finance_app
      dockerfile: Dockerfile
    container_name: tt-api
    environment:
      - DB_HOST=tt-db
      - DB_PORT=5432
    ports:
      - "5000:5000"
    networks:
      - tt
    depends_on:
      - "db"

networks:
  tt:
